# Generated by Django 5.1.1 on 2024-09-09 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added1']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added',
            new_name='date_added1',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='date_added',
            new_name='date_added2',
        ),
    ]
