# Generated by Django 5.1.1 on 2024-09-09 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_comment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-date_added']},
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='date_added1',
            new_name='date_added',
        ),
        migrations.RenameField(
            model_name='reply',
            old_name='date_added2',
            new_name='date_added',
        ),
    ]
