# Generated by Django 5.0.3 on 2024-10-24 08:11

import apps.personal.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AcademicInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições Academicas',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalInstitution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Instituições Profissionais',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('did', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('bi', models.FileField(upload_to=apps.personal.models.function_upload_to)),
                ('cv', models.FileField(upload_to=apps.personal.models.function_upload_to)),
                ('certificate_literary', models.FileField(upload_to=apps.personal.models.function_upload_to)),
                ('medical_certificate', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc1', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc2', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc3', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc4', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc5', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc6', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc7', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc8', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc9', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('other_doc10', models.FileField(blank=True, null=True, upload_to=apps.personal.models.function_upload_to)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Documentos',
                'ordering': ['user', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Formation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Formações',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='AcademicFormationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('course', models.CharField(blank=True, max_length=255, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField()),
                ('is_finished', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.academicinstitution')),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='academic_formation', to='personal.formation')),
            ],
            options={
                'verbose_name_plural': 'Formação Academica',
                'ordering': ['course'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Experiências Profissional',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalExperienceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('institution', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('years', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('profissional_experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='profissional_experience_item', to='personal.profissionalexperience')),
            ],
            options={
                'verbose_name_plural': 'Item Experiências Profissional',
                'ordering': ['institution'],
            },
        ),
        migrations.CreateModel(
            name='ProfissionalFormationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('hours', models.DecimalField(decimal_places=2, max_digits=7)),
                ('year', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('formation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='personal.formation')),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='personal.profissionalinstitution')),
            ],
            options={
                'verbose_name_plural': 'Formação Profissional',
                'ordering': ['title'],
            },
        ),
    ]
