from tkinter import *
root= Tk()
root.title("Registration Form")
root.geometry("300x300")
root.configure(background="orange")
label = Label(root,text ="Register Here!!",background="light Grey",borderwidth=10).grid(row=1,column=1)
label1 = Label(root,text ="First Name:",width=8,justify=LEFT).grid(row=4,column=0)
e1 = Entry(root).grid(row=4,column=1)
label2 = Label(root,text ="Last Name:",width=8,justify=LEFT).grid(row=5,column=0)
e2 = Entry(root).grid(row=5,column=1)
label3 = Label(root,text="Age",width=8).grid(row=6,column=0)
e3 = Entry(root).grid(row=6,column=1)
label4 = Label(root,text="Gender",width=8).grid(row=7,column=0)
val = IntVar()
Radiobutton(root,text="Male",value=1,variable=val,width=8).grid(row=7,column=1)
Radiobutton(root,text="Female",value=2,variable=val,width=8).grid(row=8,column=1)
Radiobutton(root,text="Other",value=3,variable=val,width=8).grid(row=9,column=1)
label5 = Label(root,text="Address").grid(row=10)
add = Text(width=20,height=6).grid(row=10,column=1)
label6 = Label(root,text = "Email Id:").grid(row=11)
email = Entry(root).grid(row=11,column=1)
label7 = Label(root,text = "Contact No:").grid(row=12)
contact = Entry(root).grid(row=12,column=1)
label8 = Label(root,text="Country").grid(row=13)
country = Entry(root).grid(row=13,column=1)
label9 = Label(root,text="State").grid(row=14)
state = Entry(root).grid(row=14,column=1)
label10 = Label(root,text="SELECT If you are having any following disease").grid(row=15)
val1 = IntVar()
Checkbutton(root,text="cold",variable=val1,width=8).grid(row=15,column=1)
val2 = IntVar()
Checkbutton(root,text="cough",variable=val2,width=8).grid(row=16,column=1)
val3 = IntVar()
Checkbutton(root,text="fever",variable=val3,width=8).grid(row=17,column=1)
val4 = IntVar()
Checkbutton(root,text="headache",variable=val4,width=8).grid(row=18,column=1)
mainloop()